In [1]:
import pandas as pd
import numpy as np

In [3]:
results_2021 = pd.read_csv(r'../data/results/results_2021.csv')
results_2021

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Q2,Q3,Time,Status,Points,round,race,sprint,season,year
0,44,L HAMILTON,HAM,hamilton,Mercedes,00D2BE,mercedes,Lewis,Hamilton,Lewis Hamilton,...,NaN,NaN,0 days 01:32:03.897000,Finished,25.0,1,Bahrain,False,2021,2021
1,33,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,0600EF,red_bull,Max,Verstappen,Max Verstappen,...,NaN,NaN,0 days 00:00:00.745000,Finished,18.0,1,Bahrain,False,2021,2021
2,77,V BOTTAS,BOT,bottas,Mercedes,00D2BE,mercedes,Valtteri,Bottas,Valtteri Bottas,...,NaN,NaN,0 days 00:00:37.383000,Finished,16.0,1,Bahrain,False,2021,2021
3,4,L NORRIS,NOR,norris,McLaren,FF9800,mclaren,Lando,Norris,Lando Norris,...,NaN,NaN,0 days 00:00:46.466000,Finished,12.0,1,Bahrain,False,2021,2021
4,11,S PEREZ,PER,perez,Red Bull Racing,0600EF,red_bull,Sergio,Perez,Sergio Perez,...,NaN,NaN,0 days 00:00:52.047000,Finished,10.0,1,Bahrain,False,2021,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,6,N LATIFI,LAT,latifi,Williams,005AFF,williams,Nicholas,Latifi,Nicholas Latifi,...,NaN,NaN,NaN,Accident,0.0,22,Abu Dhabi,False,2021,2021
496,99,A GIOVINAZZI,GIO,giovinazzi,Alfa Romeo Racing,900000,alfa,Antonio,Giovinazzi,Antonio Giovinazzi,...,NaN,NaN,NaN,Gearbox,0.0,22,Abu Dhabi,False,2021,2021
497,63,G RUSSELL,RUS,russell,Williams,005AFF,williams,George,Russell,George Russell,...,NaN,NaN,NaN,Gearbox,0.0,22,Abu Dhabi,False,2021,2021
498,7,K RAIKKONEN,RAI,raikkonen,Alfa Romeo Racing,900000,alfa,Kimi,Räikkönen,Kimi Räikkönen,...,NaN,NaN,NaN,Brakes,0.0,22,Abu Dhabi,False,2021,2021
499,9,NaN,MAZ,mazepin,Haas F1 Team,NaN,haas,Nikita,Mazepin,Nikita Mazepin,...,NaN,NaN,NaN,Illness,0.0,22,Abu Dhabi,False,2021,2021

In [4]:
laps_2022 = pd.read_csv(r'../data/lap_times/lap_times_2022.csv')
laps_2022

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,round,race,sprint,year
0,0 days 01:04:15.422000,VER,1,0 days 00:01:40.236000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:42.325000,...,1,2.0,False,NaN,False,False,1,Bahrain,False,2022
1,0 days 01:05:53.302000,VER,1,0 days 00:01:37.880000,2.0,1.0,NaN,NaN,0 days 00:00:31.285000,0 days 00:00:42.269000,...,1,2.0,False,NaN,False,True,1,Bahrain,False,2022
2,0 days 01:07:31.659000,VER,1,0 days 00:01:38.357000,3.0,1.0,NaN,NaN,0 days 00:00:31.499000,0 days 00:00:42.474000,...,1,2.0,False,NaN,False,True,1,Bahrain,False,2022
3,0 days 01:09:10.225000,VER,1,0 days 00:01:38.566000,4.0,1.0,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.674000,...,1,2.0,False,NaN,False,True,1,Bahrain,False,2022
4,0 days 01:10:49.102000,VER,1,0 days 00:01:38.877000,5.0,1.0,NaN,NaN,0 days 00:00:31.498000,0 days 00:00:42.854000,...,1,2.0,False,NaN,False,True,1,Bahrain,False,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24877,0 days 01:37:58.468000,ALO,14,0 days 00:01:31.819000,23.0,2.0,NaN,NaN,0 days 00:00:18.373000,0 days 00:00:38.859000,...,1,12.0,False,NaN,False,True,22,Abu Dhabi,False,2022
24878,0 days 01:39:29.047000,ALO,14,0 days 00:01:30.579000,24.0,2.0,NaN,NaN,0 days 00:00:18.351000,0 days 00:00:38.485000,...,1,11.0,False,NaN,False,True,22,Abu Dhabi,False,2022
24879,0 days 01:41:00.112000,ALO,14,0 days 00:01:31.065000,25.0,2.0,NaN,NaN,0 days 00:00:18.337000,0 days 00:00:39.215000,...,1,11.0,False,NaN,False,True,22,Abu Dhabi,False,2022
24880,0 days 01:42:30.800000,ALO,14,0 days 00:01:30.688000,26.0,2.0,NaN,NaN,0 days 00:00:18.295000,0 days 00:00:39.038000,...,1,10.0,False,NaN,False,True,22,Abu Dhabi,False,2022
24881,0 days 01:44:03.978000,ALO,14,0 days 00:01:33.178000,27.0,2.0,NaN,0 days 01:44:02.950000,0 days 00:00:18.250000,0 days 00:00:38.903000,...,1,10.0,False,NaN,False,False,22,Abu Dhabi,False,2022